name: lab3
channels:
  - defaults
dependencies:
  - python=3.9.13
  - pip
  - pip:
    - fastapi==0.103.0
    - uvicorn==0.23.2
    - pydantic==2.3.0
    - pandas==2.1.0
    - numpy==1.25.2
    - scikit-learn==1.3.0 
    - mlflow==2.6.0
    - xgboost==1.7.6