# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "MLOps_Professional/lab1/sample/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "MLOps_Professional/lab8/sample/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "MLOps_Professional/mlops_capstone/robot_maintenance/src/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "MLOps_Professional/mlops_capstone/app_frontend/" # Location of package manifests
    schedule:
      interval: "monthly"
