name: lab7
channels:
  - defaults
dependencies:
  - python=3.9.13
  - pip:
    - fastapi==0.101.1
    - uvicorn==0.23.2
    - pydantic==2.2.0
    - pandas==2.0.3
    - numpy==1.25.2
    - scikit-learn==1.3.0
    - mlflow==2.6.0
    - xgboost==1.7.6
    - daal4py==2023.2.1
